// Storage Manager MCP — Definition
// Lets users upload files via Claude and get a 24-hour signed link

export const STORAGE_MCP_DEFINITION = {
  slug: 'storage-manager',
  name: 'Storage Manager',
  description: 'Upload files through Claude and get a 24-hour shareable link. Attach a file in your Claude chat, then say "upload this file". Supports upload from URL and saving Claude-generated content as files.',
  icon: '🗂️',
  category: 'productivity',
  version: '1.0.0',
  author: 'EternalMCP',
  verified: true,
  rating: 5.0,
  installs: 0,
  tags: ['storage', 'upload', 'files', 'sharing', 'links'],
  oauth_provider: null as null,
  oauth_scopes: [] as string[],
  requiresOAuth: false,
  creditCost: 0,
  permissions: [
    { label: 'Upload files to EternalMCP secure storage', granted: true },
    { label: 'Generate 24-hour signed download links', granted: true },
    { label: 'List and manage your stored files', granted: true },
    { label: 'Access your personal accounts or data', granted: false },
  ],
  tools: [
    {
      name: 'upload_file',
      description: 'Upload a file that is attached in the current Claude chat. The file content should be passed as a base64-encoded string. Returns a download link valid for 24 hours. Max file size: 20 MB. Max 10 files total.',
      inputSchema: {
        type: 'object',
        properties: {
          content_base64: {
            type: 'string',
            description: 'The file content encoded as a base64 string',
          },
          filename: {
            type: 'string',
            description: 'The name to save the file as (e.g. "invoice.pdf", "photo.jpg")',
          },
          mime_type: {
            type: 'string',
            description: 'MIME type of the file (e.g. "application/pdf", "image/jpeg"). If unsure, pass "application/octet-stream".',
          },
        },
        required: ['content_base64', 'filename'],
      },
    },
    {
      name: 'upload_from_url',
      description: 'Download a file from a public URL and store it, returning a 24-hour download link. Useful for re-hosting files from the internet. Max 20 MB.',
      inputSchema: {
        type: 'object',
        properties: {
          url: {
            type: 'string',
            description: 'Public URL of the file to download and store',
          },
          filename: {
            type: 'string',
            description: 'Name to save the file as. If omitted, derived from the URL.',
          },
        },
        required: ['url'],
      },
    },
    {
      name: 'save_as_file',
      description: 'Save text content (generated by Claude or provided by user) as a file and return a 24-hour download link.',
      inputSchema: {
        type: 'object',
        properties: {
          content: {
            type: 'string',
            description: 'The text content to save',
          },
          filename: {
            type: 'string',
            description: 'Filename without extension (e.g. "my-report", "notes")',
          },
          format: {
            type: 'string',
            enum: ['txt', 'md', 'html', 'json', 'csv'],
            description: 'File format/extension. Default: txt',
          },
        },
        required: ['content', 'filename'],
      },
    },
    {
      name: 'list_files',
      description: 'List all files currently stored in your EternalMCP storage. Shows filename, size, upload time, expiry, and a fresh 24-hour download link for each.',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
      },
    },
    {
      name: 'delete_file',
      description: 'Delete a stored file by its ID (from list_files). Frees up storage space.',
      inputSchema: {
        type: 'object',
        properties: {
          file_id: {
            type: 'string',
            description: 'The file ID from list_files',
          },
        },
        required: ['file_id'],
      },
    },
  ],
} as const
